name: Industrialisation continue sur le serveur AWS (Tomcat)
on: [push]
jobs:
  deploy_aws:
    # Configuration pour le déploiement AWS 
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf khachchab.war *
      - name: Copy file via SSH password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "khachchab.war"
          target: "/opt/tomcat/webapps"

  ipfs_backup:
    # L'action IPFS Backup 
    name: Backup to IPFS
    needs: deploy_aws  # Le job "ipfs_backup" dépend du succès du job "deploy_aws"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf fichier.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add fichier.war
        shell: alpine.sh --root {0}
