name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf GuyJustine.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.FTP_HOST_DNS }}
        username: ${{ secrets.FTP_USERNAME }}
        key: ${{ secrets.FTP_EC2_SSH_KEY }}
        port: ${{ secrets.FTP_DEPLOY_PORT }}
        source: "GuyJustine.war"
        target: "/opt/tomcat/webapps"
