name: Sauvegarde d'un fichier sur le réseau IPFS

on: 
  push:
    branches:
      - master

jobs:
  deploy_aws:
    name: Deploy AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Ajoutez ici les étapes de déploiement AWS

  deploy_ipfs:
    name: Sauvegarde sur IPFS
    runs-on: ubuntu-latest
    needs: deploy_aws
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create WAR file
        run: jar cvf fichier.war *

      - name: Setup Alpine
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15

      - name: Install and start IPFS
        run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}

      - name: Save WAR file to IPFS
        run: |
          ls -la
          ipfs swarm peers
          ipfs add fichier.war
        shell: alpine.sh --root {0}
